title: ğŸ°
theme: jekyll-theme-slate
description: by <a href="https://github.com/insanj">@insanj</a>
show_downloads: true
repository_url: https://github.com/insanj/familynames
author:
  name: "Julian Weiss"
